### ISSUE TITLE
List used PSTN numbers

### ISSUE THREAD

**Issue by nicosalvadore** [erik365online/MicrosoftTeamsUserNumberAssigner#1]
Hello Erik,

I've read your blog post and it's an interesting project !

Configuring Direct Routing for new teams users is something my colleagues and I have to to pretty often.
One of the challenge we have is knowing what number is already in use in the tenant.

Do you think that it would be possible to list all numbers already assigned ?
Maybe we could add a button that would pop an additionnal window, this window would list all numbers and the UPN they are associated with, sorted by ascending numbers.

Let me know your thoughts this feature :)

**Comment by erik365online** [comment]
Hi @nicosalvadore, 

Thank you for your feedback!

That's an interesting idea.  However, I'm not sure where I should put existing numbers in this GUI in a way that it makes sense? I wonder if I could add a list box which displays some more output, and may lists all assigned numbers incl. Users UPN. Or add a button or something which delivers this output as a CSV or txt file.

I'll keep that idea in mind the next time I'll have some time to enhance this tool.

I'm still hoping that Microsoft will sooner or later bring this basic capabilitiy into the Teams Admin Center for TDR, anyway.

Best Regards,
Erik

**Comment by nicosalvadore** [comment]
Hi @erik365online !
I think a list box would be a great first addition. An export to csv would be good to, but I think it should be an additionnal feature, on top of the listbox.

I think that Microsoft is not in a hurry to bring this feature to the TAC. If you want to manage your PSTN numbers from the GUI, they want you to buy a calling plan.

Thanks,
Nicolas

**Comment by erik365online** [comment]
Hi @nicosalvadore,
Thank you. 

I'll have to check if a list box is ok, I mean it would be ok for probably a few hundred numbers but not for more. It might take to long to load and list all numbers. Or I have to consider a limitation or button to load the next 100+ numbers or something.
At the moment I'm consindering a number validation check box, to enter a number check if it is available or not.
But these are just ideas at the moment.

BR,
Erik

**Comment by erik365online** [comment]
In the latest release V0.3 the PowerShell window in the background lists user details like phone number, calling policy, voice routing policy as soon as a user is selected. For a bigger list there is no space available in the existing box. I'll keep that in mind for a future release.
