### ISSUE TITLE
Error when running

### ISSUE THREAD

**Issue by neilmcco** [erik365online/MicrosoftTeamsUserNumberAssigner#2]
Hi Sir,
I'm new to the PowerShel and I would love to be able to use your code.
Every time that I try to use the code I receive the following error.
Any help will be appreciated.
Line |
 219 |  … ata-ga-click="(Logged out) Header, go to Features">Features <span cla …
     |                                                                ~
     | The '<' operator is reserved for future use.

Regards
Neil

**Comment by erik365online** [comment]
Hello @neilmcco,
Thank you for your feedback. However, I could not reproduce the issue.
Checking Line 219 in the code does not indicate an issue.

Are the requirements satisfied? E.g. Windows 10, PowerShell 5+, Teams PowerShell Module 2.3.1 installed?
Best Regards
Erik
